# This is a basic workflow to help you get started with Actions

name: Hello World
on:
  push:
    branches: [ "main" ]
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Echo text
        run: echo "Hello, world!"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
